### ISSUE TITLE
duplicate key: substrate-build-script-utils for key build-dependencies

### ISSUE THREAD

**Issue by AuroraLantean** [sacha-l/kickstart-substrate#12]
**Description**

rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file ../kitties/Cargo.toml, cargo 1.58.0 (f01b232bc 2022-01-19): Failed to run `"cargo" "metadata" "--format-version" "1" "--manifest-path" "../kitties/Cargo.toml" "--filter-platform" "x86_64-unknown-linux-gnu"`: `cargo metadata` exited with an error: error: failed to load manifest for workspace member `../kitties/node` Caused by: failed to parse manifest at `../kitties/node/Cargo.toml` Caused by: could not parse input as TOML Caused by: duplicate key: `substrate-build-script-utils` for key `build-dependencies` at line 70 column 1

inside my ../kitties/node/Cargo.toml
those two below seem to have conflict...
Line 19:
```
[build-dependencies.substrate-build-script-utils]
git = 'https://github.com/paritytech/substrate.git'
tag = 'devhub/latest'
version = '3.0.0'
```

Line 67:
```
[build-dependencies]
substrate-build-script-utils = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git", tag = "devhub/latest" }

```

**Steps to Reproduce**

Follow the tutorial on https://docs.substrate.io/tutorials/v3/kitties/pt1/

After using the kickstart command, type in "kitties" and "kitties"...

**Expected vs. Actual Behavior**

VS Code plugin rust-analyzer shows above error

**Environment**

VS Code the latest
rust-analyzer v0.3.933
Linux Mint the latest
Rust 1.58.1

**Logs, Errors or Screenshots**

See above

**Additional Information**

none

**Comment by Aideepakchaudhary** [comment]
@AuroraLantean have you got any solution for this issue?

**Comment by sacha-l** [comment]
@Aideepakchaudhary are you experiencing the same issue? The template has been updated since this was flagged and should no longer be an issue. Let me know. In any case, I'm moving back to this syntax:

```toml
[build-dependencies]
substrate-build-script-utils = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git", tag = "devhub/latest" }
```

so if you have an older template, just remove the other `build-dependencies` declaration.

**Comment by Aideepakchaudhary** [comment]
@sacha-l  I'm Using the latest template but experience the same issue. If i remove the [build-dependencies] from node/cargo.toml then i get this error : 
error: failed to get `frame-benchmarking` as a dependency of package `node-template v4.0.0-dev (D:\template\node)`

Caused by:
  failed to load source for dependency `frame-benchmarking`

Caused by:
  Unable to update https://github.com/paritytech/substrate.git?tag=devhub/latest#e6fbbd5c      

Caused by:
  object not found - no match for id (e6fbbd5cdf72a5ed7fd65138072ed1f8a320a33d); class=Odb (9); code=NotFound (-3)

**Comment by sacha-l** [comment]
Please try again with a fresh clone. The template has been updated and now uses Substrate's `polkadot-v0.9.17` branch, pulling in new updates that should fix the issues above. Let me know if this works!

**Comment by Aideepakchaudhary** [comment]
Yeah Now it works fine. Thank you
