### ISSUE TITLE
Request: Clarify applicable source code license

### ISSUE THREAD

**Issue by kwvg** [sacha-l/kickstart-substrate#9]
`kickstart-substrate` is a really helpful tool and expanding on it could help a lot of beginner projects. Thank you for your contributions!

### Description

Kickstart is licensed under the MIT License and the Substrate template it bootstraps is under the Unlicense relying on GPLv3/Apache+MIT components, so far the licensing chain is _almost_ clear. 

A clarification on the licensing of the `kickstart-substrate` would help complete that licensing chain.

### Proposed Solution

* Clarification in comments
* A commit containing a `LICENSE` file

**Comment by sacha-l** [comment]
Hi @kittywhiskers - glad its useful for you, thanks for the nice comment. 

This is a very fair point. I just added a licence, using Apache 2.0 to be consistent with Substrate. 

How does this look to you?

**Comment by kwvg** [comment]
Sounds great! I'll close this cause it's no longer an issue!
